import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Nav from '../pages/components/navbar';
import SocialProfileWithImage from '../pages/components/body';
import ExperienceTimeLine from './components/experience';
import SkillsUp from './components/skills';
import { Grid, Heading } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Raysson Ornelas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <SocialProfileWithImage />
      <Heading mt={10} textAlign="center">
        Experience
      </Heading>
      <main className={styles.main}>
        <Grid templateColumns="repeat(2, 1fr)" gap={6}>
          <ExperienceTimeLine />
          <ExperienceTimeLine />
          <ExperienceTimeLine />
          <ExperienceTimeLine />
        </Grid>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
