import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Nav from '../pages/components/navbar';
import SocialProfileWithImage from '../pages/components/body';
import ExperienceTimeLine from './components/experience';
import SkillsUp from './components/skills';
import { Grid, Heading, Center } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Raysson Ornelas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <SocialProfileWithImage />
      <Heading mt={10} textAlign="center">
        Experience
      </Heading>
      <Center py={5}>
        <Grid
          templateColumns={{
            base: 'auto',
            md: 'repeat(2,1fr)',
            lg: 'repeat(4, 1fr)',
          }}
          w="90%"
          gap={6}>
          <ExperienceTimeLine />
          <ExperienceTimeLine />
          <ExperienceTimeLine />
          <ExperienceTimeLine />
        </Grid>
      </Center>
      <Heading mt={5} textAlign="center">
        Skills
      </Heading>
      <SkillsUp />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
